@echo off

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_512K.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_512K.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_512K.zip" "D:\Work\GitHub\UnifiedFirmware\LCD Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_512K.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_512K.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_512K.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_512K.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\CrealityV4X_512K\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_256K.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_256K.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_256K.zip" "D:\Work\GitHub\UnifiedFirmware\LCD Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_256K.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_256K.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_256K.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_CrealityV4X_256K.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\CrealityV4X_256K\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\SKR_E3_Mini\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini_V3.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini_V3.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini_V3.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini_V3.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini_V3.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_SKR_E3_Mini_V3.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\SKR_E3_Mini_V3\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\EZBoard V1 Installation Guide"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\Pre-Compiled Binaries\EZBoard V1 Pre-Compiled Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\TH3D_EZBoardLite\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2.zip" "D:\Work\GitHub\UnifiedFirmware\EZBoard V2 Installation Guide"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2.zip" "D:\Work\GitHub\UnifiedFirmware\Pre-Compiled Binaries\EZBoard V2 Pre-Compiled Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\TH3D_EZBoardV2\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\EZBoard Installation Guide"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardLite_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\TH3D_EZBoardLite_DIY\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2_DIY.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\EZBoard V2 Installation Guide"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_TH3D_EZBoardV2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\TH3D_EZBoardV2_DIY\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_Robin_Mini.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\MKS_Robin_Mini\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Anet_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Anet_Melzi\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\AnyCubic_Melzi\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_AnyCubic_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\AnyCubic_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Creality_Melzi\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_ADIM_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\ADIM_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Alfawise_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Alfawise_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Artillery_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Artillery_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Creality_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Creality_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sovol_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Sovol_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Sunlu_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Sunlu_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Wanhao_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Tevo_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Tevo_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Tevo_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Tevo_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Tevo_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Tevo_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Tevo_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Geeetech_Ramps.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Geeetech_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Geeetech_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Geeetech_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Geeetech_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Geeetech_Ramps.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Geeetech_Ramps\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_MKS_SGen_L_V2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\MKS_SGen_L_V2_DIY\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_DIY.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\BTT_SKR_2_DIY\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_F429_DIY.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_F429_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_F429_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_F429_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_F429_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_BTT_SKR_2_F429_DIY.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\BTT_SKR_2_F429_DIY\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Kingroon_V1_2.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Kingroon_V1_2\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Melzi.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Firmware"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\TH3D Installation Guides"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\README.md"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\STL File Download.txt"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_Wanhao_Melzi.zip" "D:\Work\GitHub\UnifiedFirmware\Board_Configs\Wanhao_Melzi\Firmware"

"C:\Program Files\7-Zip\7z.exe" d -tZip "D:\Work\Unified2Zips\TH3D_Unified2_STL_Pack.zip"
"C:\Program Files\7-Zip\7z.exe" a -tZip "D:\Work\Unified2Zips\TH3D_Unified2_STL_Pack.zip" "D:\Work\GitHub\UnifiedFirmware\STL Files"